name: Hello World
run-name: executed by $${{ github.actor }} on branch ${{ github.ref}} of repository ${{ github.repository }}
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello: # job name
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.check_status.outputs.result}}
        steps:
            - uses: actions/checkout@v4
            - name: echo hello world step  # optional
              run: |
                for i in {1..10}
                do
                    echo 'Hello, World!'
                    sleep 1s
                done
              shell: bash # optional
            - name: check status
              id: check_status
              # run: echo '::set-output name=result::false'
              run: echo "result=true" >> $GITHUB_OUTPUT
    goodbye: # job name
        runs-on: macos-latest
        needs: hello   # wait for hello job
        if: needs.hello.outputs.result == 'true'
        steps:
            #- name: echo goodbye world step
            - run: echo "Goodbye, World!"
            # shell: bash

 