# Name of the workflow
name: GitHub Action Input/Output

# Name of the workflow instance
run-name: ${{ github.actor }} is testing out GitHub Actions on ${{ github.repository }}🚀

# Specify how the workflow is triggered
# In this scenario, the workflow is manually dispatched.
# And users can specify an input text message
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'A text message'

# Specify a list of jobs to run
jobs:
  job_1: # name of job 2
    runs-on: ubuntu-latest

    # job output parameters
    outputs:
      job_1_output: ${{ steps.step_3.outputs.step_3_output }}

    steps:
      - name: job_1 step_1 # name of step 1
        id: step_1
        # output the result to 'step_1_output'
        run: echo 'step_1_output=Hi ${{ inputs.message }}' >> $GITHUB_OUTPUT
        shell: bash

      - name: job_1 step_2 # name of step 2
        # Reference the output from step 1
        run: echo '${{ steps.step_1.outputs.step_1_output }}'

      - name: job_1 step_3
        id: step_3
        run: echo 'step_3_output='${{ steps.step_1.outputs.step_1_output }} from ${{ github.actor }}' >> $GITHUB_OUTPUT
        shell: bash

  job_2: # name of job 2
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: job_1 step_2 # name of step 2
      # Reference the output from step 1
        run: echo 'This message is from job_1.  ${{ needs.job_1.outputs.job_1_output }}'
        shell: bash
  